# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GUI import *
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle(" ")
        MainWindow.setWindowIcon(QIcon(resource_path("Icons/transparentIcon.svg")))
        MainWindow.resize(1128, 828)
        MainWindow.setMinimumSize(QtCore.QSize(200, 40))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(243, 252, 255);  /* Dark background color */\n"
"\n"
"    border-radius: 10px;        /* Rounded corners */\n"
"    padding: 10px;              /* Inner padding */\n"
"}\n"
"\n"
"QMainWindow::title {\n"
"    color: white;               /* White title bar text */\n"
"    background-color: rgb(255, 255, 127);  /* Teal background for the title bar */\n"
"    padding: 5px;               /* Padding around the title */\n"
"    font-size: 16px;            /* Title text size */\n"
"    text-align: center;         /* Centered title text */\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"    background-color: #E74C3C;  /* Red for splitters */\n"
"    width: 3px;                 /* Width of the splitter */\n"
"    height: 3px;                /* Height of the splitter */\n"
"}\n"
"\n"
"QMainWindow::statusbar {\n"
"    background-color:rgb(245, 245, 245);  /* Darker background for the status bar */\n"
"    color: white;               /* White text */\n"
"    border-top: 1px solid rgb(255, 85, 0); /* Teal border on top */\n"
"}\n"
"")
        
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleFrame = GradientWidget(self.centralwidget)
        self.titleFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleFrame.sizePolicy().hasHeightForWidth())
        self.titleFrame.setSizePolicy(sizePolicy)
        self.titleFrame.setMinimumSize(QtCore.QSize(0, 280))
        self.titleFrame.setMaximumSize(QtCore.QSize(16777215, 280))
        self.titleFrame.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(True)
        font.setWeight(75)
        self.titleFrame.setFont(font)
        self.titleFrame.setAutoFillBackground(False)
        self.titleFrame.setStyleSheet("QFrame {\n"
"    \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 rgba(243, 200, 205, 255), stop: 1 rgba(181, 210, 228, 255));\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.titleFrame)
        self.verticalLayout.setContentsMargins(2, 0, 2, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(140, 25))
        self.frame_7.setMaximumSize(QtCore.QSize(200, 25))
        self.frame_7.setStyleSheet("QFrame {\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:12px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.seachEditLine = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seachEditLine.sizePolicy().hasHeightForWidth())
        self.seachEditLine.setSizePolicy(sizePolicy)
        self.seachEditLine.setMinimumSize(QtCore.QSize(50, 20))
        self.seachEditLine.setMaximumSize(QtCore.QSize(239, 16777215))
        self.seachEditLine.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.seachEditLine.setObjectName("seachEditLine")
        self.horizontalLayout_11.addWidget(self.seachEditLine)
        self.label = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(20, 20))
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setStyleSheet("QLabel{\n"
"background-color:transparent;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Icons/Icons/Search.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.gridLayout_2.addWidget(self.frame_7, 0, 5, 1, 1)
        self.presentationNameLabel = QtWidgets.QLabel(self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presentationNameLabel.sizePolicy().hasHeightForWidth())
        self.presentationNameLabel.setSizePolicy(sizePolicy)
        self.presentationNameLabel.setMinimumSize(QtCore.QSize(250, 0))
        self.presentationNameLabel.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.presentationNameLabel.setFont(font)
        self.presentationNameLabel.setStyleSheet("QLabel{\n"
"            background-color:transparent;\n"
"}")
        self.presentationNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.presentationNameLabel.setScaledContents(True)
        self.presentationNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.presentationNameLabel.setWordWrap(True)
        self.presentationNameLabel.setObjectName("presentationNameLabel")
        self.gridLayout_2.addWidget(self.presentationNameLabel, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.appIconLabel = QtWidgets.QLabel(self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appIconLabel.sizePolicy().hasHeightForWidth())
        self.appIconLabel.setSizePolicy(sizePolicy)
        self.appIconLabel.setMinimumSize(QtCore.QSize(40, 60))
        self.appIconLabel.setMaximumSize(QtCore.QSize(40, 60))
        self.appIconLabel.setMouseTracking(False)
        self.appIconLabel.setStyleSheet("QLabel{\n"
"            background-color:transparent;\n"
"}")
        self.appIconLabel.setText("")
        self.appIconLabel.setPixmap(QtGui.QPixmap(":/frames/Icons/gesturaLastIcon.png"))
        self.appIconLabel.setScaledContents(True)
        self.appIconLabel.setObjectName("appIconLabel")
        self.horizontalLayout_2.addWidget(self.appIconLabel)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(5, 10, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.appNameLabel = QtWidgets.QLabel(self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appNameLabel.sizePolicy().hasHeightForWidth())
        self.appNameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.appNameLabel.setFont(font)
        self.appNameLabel.setStyleSheet("QLabel{\n"
"            background-color:transparent;\n"
"}")
        self.appNameLabel.setScaledContents(False)
        self.appNameLabel.setObjectName("appNameLabel")
        self.verticalLayout_6.addWidget(self.appNameLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 2, 1)
        self.pushButton = QtWidgets.QPushButton(self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(70, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 84, 252);\n"
"    color: white;\n"
"\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(68,120, 222);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(171, 226, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #95a5a6;\n"
"    border: 2px solid #7f8c8d;\n"
"    color: #bdc3c7;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Share 2active"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 2)
        self.frame_8 = QtWidgets.QFrame(self.titleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(200, 70))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_8.setStyleSheet("QFrame {\n"
"            \n"
"    background-color: transparent;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.userPhotoLabel = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userPhotoLabel.sizePolicy().hasHeightForWidth())
        self.userPhotoLabel.setSizePolicy(sizePolicy)
        self.userPhotoLabel.setMinimumSize(QtCore.QSize(40, 40))
        self.userPhotoLabel.setMaximumSize(QtCore.QSize(40, 40))
        self.userPhotoLabel.setStyleSheet("QLabel{\n"
"            background-color:transparent;\n"
"}")
        self.userPhotoLabel.setText("")
        self.userPhotoLabel.setPixmap(QtGui.QPixmap(":/Icons/Avatar.png"))
        self.userPhotoLabel.setScaledContents(True)
        self.userPhotoLabel.setObjectName("userPhotoLabel")
        self.horizontalLayout_3.addWidget(self.userPhotoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userNameLabel = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userNameLabel.sizePolicy().hasHeightForWidth())
        self.userNameLabel.setSizePolicy(sizePolicy)
        self.userNameLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.userNameLabel.setStyleSheet("QLabel{\n"
"            background-color:transparent;\n"
"}")
        self.userNameLabel.setObjectName("userNameLabel")
        self.verticalLayout_2.addWidget(self.userNameLabel)
        self.userAddressLabel = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userAddressLabel.sizePolicy().hasHeightForWidth())
        self.userAddressLabel.setSizePolicy(sizePolicy)
        self.userAddressLabel.setMinimumSize(QtCore.QSize(0, 9))
        self.userAddressLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.userAddressLabel.setStyleSheet("QLabel{\n"
"            background-color:transparent;\n"
"}")
        self.userAddressLabel.setObjectName("userAddressLabel")
        self.verticalLayout_2.addWidget(self.userAddressLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addWidget(self.frame_8, 0, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.titleFrame)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 220))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 220))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setStyleSheet("\n"
"QTabBar::tab {\n"
"    background: transparent;\n"
"    border: none;\n"
"  padding:5px;\n"
"    margin:2;\n"
"    font-size:13px;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: rgb(225, 101, 13);\n"
"    border-bottom: 5px solid orange;\n"
"     padding: 10px 10px;\n"
"    font-size:13px; /* Increased font size for selected tab */\n"
"         font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    color: black;\n"
"    border-bottom:1px solid black;\n"
"    font-size: 13px;\n"
" \n"
"}\n"
"QTabBar::tab:hover {\n"
"     color:black;\n"
"    border-bottom: 3px solid orange;\n"
"    \n"
"    font-size:13px; /* Increased font size for selected tab */\n"
"    font-weight: bold; /* Makes the selected tab title bold */\n"
"   \n"
"}\n"
"QPushButton:pressed:hover {\n"
"    color: rgb(225, 101, 13);\n"
"    border-bottom: 5px solid orange;\n"
"     padding: 10px 10px;\n"
"    font-size:13px; /* Increased font size for selected tab */\n"
"         font-weight: bold;\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"")
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.FileTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileTab.sizePolicy().hasHeightForWidth())
        self.FileTab.setSizePolicy(sizePolicy)
        self.FileTab.setStyleSheet("""
background-color:transparent;
""")
        self.FileTab.setObjectName("FileTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FileTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.FileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 120))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        # Create the shadow effect
      
        self.verticalLayout_5.addWidget(self.frame)
        self.tabWidget.addTab(self.FileTab, "")
        self.homeTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeTab.sizePolicy().hasHeightForWidth())
        self.homeTab.setSizePolicy(sizePolicy)
        self.homeTab.setObjectName("homeTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.homeTab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.homeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 115))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
    
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(5, 2, 2, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fontGroupBox = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.fontGroupBox.setFont(font)
        self.fontGroupBox.setObjectName("fontGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fontGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textColorButton = QtWidgets.QPushButton(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textColorButton.sizePolicy().hasHeightForWidth())
        self.textColorButton.setSizePolicy(sizePolicy)
        self.textColorButton.setMinimumSize(QtCore.QSize(30, 0))
        self.textColorButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.textColorButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/text-editor.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.textColorButton.setIcon(icon1)
        self.textColorButton.setObjectName("textColorButton")
        self.gridLayout_3.addWidget(self.textColorButton, 3, 5, 1, 1)
        self.underlineButton = QtWidgets.QPushButton(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.underlineButton.sizePolicy().hasHeightForWidth())
        self.underlineButton.setSizePolicy(sizePolicy)
        self.underlineButton.setMinimumSize(QtCore.QSize(30, 0))
        self.underlineButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.underlineButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/Underline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlineButton.setIcon(icon2)
        self.underlineButton.setCheckable(True)
        self.underlineButton.setAutoExclusive(False)
        self.underlineButton.setObjectName("underlineButton")
        self.gridLayout_3.addWidget(self.underlineButton, 3, 2, 1, 1)
        self.boldButton = QtWidgets.QPushButton(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boldButton.sizePolicy().hasHeightForWidth())
        self.boldButton.setSizePolicy(sizePolicy)
        self.boldButton.setMinimumSize(QtCore.QSize(30, 0))
        self.boldButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.boldButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/bold-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldButton.setIcon(icon3)
        self.boldButton.setCheckable(True)
        self.boldButton.setAutoExclusive(False)
        self.boldButton.setObjectName("boldButton")
        self.gridLayout_3.addWidget(self.boldButton, 3, 0, 1, 1)
        self.textColorFrame = QtWidgets.QFrame(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textColorFrame.sizePolicy().hasHeightForWidth())
        self.textColorFrame.setSizePolicy(sizePolicy)
        self.textColorFrame.setMinimumSize(QtCore.QSize(30, 4))
        self.textColorFrame.setMaximumSize(QtCore.QSize(30, 4))
        self.textColorFrame.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 0);\n"
"border:1px;\n"
"\n"
"}")
        self.textColorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textColorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textColorFrame.setObjectName("textColorFrame")
        self.gridLayout_3.addWidget(self.textColorFrame, 4, 5, 1, 1)
        self.strikeButton = QtWidgets.QPushButton(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strikeButton.sizePolicy().hasHeightForWidth())
        self.strikeButton.setSizePolicy(sizePolicy)
        self.strikeButton.setMinimumSize(QtCore.QSize(30, 0))
        self.strikeButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.strikeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.strikeButton.setIcon(icon4)
        self.strikeButton.setCheckable(True)
        self.strikeButton.setAutoExclusive(False)
        self.strikeButton.setObjectName("strikeButton")
        self.gridLayout_3.addWidget(self.strikeButton, 3, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(2, 0))
        self.line_2.setMaximumSize(QtCore.QSize(2, 30))
        self.line_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(147, 147, 147); /* Change this to the desired color */\n"
"    width: 2px; /* Adjust thickness if needed */\n"
"}\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 3, 4, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.fontComboBox = QtWidgets.QFontComboBox(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        self.fontComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.fontComboBox.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setStyleSheet("QFontComboBox {\n"
"    border: 2px solid rgb(154, 154, 154);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: rgb(240, 240, 240); /* Light background */\n"
"    color: rgb(50, 50, 50); /* Text color */\n"
"}\n"
"\n"
"QFontComboBox::drop-down {\n"
"    border-left: 1px solid rgb(154, 154, 154);\n"
"    background-color: rgb(220, 220, 220);\n"
"    width: 20px;\n"
"}\n"
"\n"
"QFontComboBox::down-arrow {\n"
"    image: url(C:/Users/hamda/Desktop/GesturaApp versions/GesturaApp  version 0_2/gesturaTesting/Icons/Chevron down.svg); /* Customize with your own icon */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QFontComboBox:hover {\n"
"    border-color: rgb(100, 100, 100); /* Darker border on hover */\n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"")
        self.fontComboBox.setEditable(True)
        self.fontComboBox.setDuplicatesEnabled(False)
        self.fontComboBox.setFrame(True)
        self.fontComboBox.setWritingSystem(QtGui.QFontDatabase.Latin)
        font = QtGui.QFont()
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout_23.addWidget(self.fontComboBox)
        self.fontSizeSpinBox = QtWidgets.QSpinBox(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontSizeSpinBox.sizePolicy().hasHeightForWidth())
        self.fontSizeSpinBox.setSizePolicy(sizePolicy)
        self.fontSizeSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.fontSizeSpinBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.fontSizeSpinBox.setStyleSheet("QSpinBox {\n"
"    border: 2px solid rgb(154, 154, 154);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: rgb(240, 240, 240); /* Light background */\n"
"    color: rgb(50, 50, 50); /* Text color */\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    border-left: 1px solid rgb(154, 154, 154);\n"
"    background-color: rgb(220, 220, 220);\n"
"    width: 20px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    border-left: 1px solid rgb(154, 154, 154);\n"
"    background-color: rgb(220, 220, 220);\n"
"    width: 20px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(C:/Users/hamda/Desktop/GesturaApp versions/GesturaApp  version 0_2/gesturaTesting/Icons/Chevron up.svg); /* Replace with your resource path */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(C:/Users/hamda/Desktop/GesturaApp versions/GesturaApp  version 0_2/gesturaTesting/Icons/Chevron down.svg); /* Replace with your resource path */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border-color: rgb(100, 100, 100); /* Darker border on hover */\n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"")
        self.fontSizeSpinBox.setObjectName("fontSizeSpinBox")
        self.horizontalLayout_23.addWidget(self.fontSizeSpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_23, 2, 0, 1, 7)
        self.italicButton = QtWidgets.QPushButton(self.fontGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.italicButton.sizePolicy().hasHeightForWidth())
        self.italicButton.setSizePolicy(sizePolicy)
        self.italicButton.setMinimumSize(QtCore.QSize(30, 0))
        self.italicButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.italicButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/Italic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicButton.setIcon(icon5)
        self.italicButton.setCheckable(True)
        self.italicButton.setAutoExclusive(False)
        self.italicButton.setObjectName("italicButton")
        self.gridLayout_3.addWidget(self.italicButton, 3, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.fontGroupBox)
        self.paragraphGroupBox = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(True)
        font.setWeight(75)
        self.paragraphGroupBox.setFont(font)
        self.paragraphGroupBox.setObjectName("paragraphGroupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.paragraphGroupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.alignLeftButton = QtWidgets.QPushButton(self.paragraphGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignLeftButton.sizePolicy().hasHeightForWidth())
        self.alignLeftButton.setSizePolicy(sizePolicy)
        self.alignLeftButton.setMinimumSize(QtCore.QSize(50, 0))
        self.alignLeftButton.setMaximumSize(QtCore.QSize(30, 50))
        self.alignLeftButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/align-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alignLeftButton.setIcon(icon6)
        self.alignLeftButton.setIconSize(QtCore.QSize(30, 30))
        self.alignLeftButton.setCheckable(True)
        self.alignLeftButton.setAutoExclusive(True)
        self.alignLeftButton.setObjectName("alignLeftButton")
        self.horizontalLayout_5.addWidget(self.alignLeftButton)
        self.alignCenterButton = QtWidgets.QPushButton(self.paragraphGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignCenterButton.sizePolicy().hasHeightForWidth())
        self.alignCenterButton.setSizePolicy(sizePolicy)
        self.alignCenterButton.setMinimumSize(QtCore.QSize(50, 50))
        self.alignCenterButton.setMaximumSize(QtCore.QSize(50, 50))
        self.alignCenterButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/format.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alignCenterButton.setIcon(icon7)
        self.alignCenterButton.setIconSize(QtCore.QSize(30, 30))
        self.alignCenterButton.setCheckable(True)
        self.alignCenterButton.setAutoExclusive(True)
        self.alignCenterButton.setObjectName("alignCenterButton")
        self.horizontalLayout_5.addWidget(self.alignCenterButton)
        self.alignRightButton = QtWidgets.QPushButton(self.paragraphGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignRightButton.sizePolicy().hasHeightForWidth())
        self.alignRightButton.setSizePolicy(sizePolicy)
        self.alignRightButton.setMinimumSize(QtCore.QSize(50, 50))
        self.alignRightButton.setMaximumSize(QtCore.QSize(50, 50))
        self.alignRightButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/align-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alignRightButton.setIcon(icon8)
        self.alignRightButton.setIconSize(QtCore.QSize(30, 30))
        self.alignRightButton.setCheckable(True)
        self.alignRightButton.setAutoExclusive(True)
        self.alignRightButton.setObjectName("alignRightButton")
        self.horizontalLayout_5.addWidget(self.alignRightButton)
        self.horizontalLayout_4.addWidget(self.paragraphGroupBox)
        self.drawingGroupBox = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.drawingGroupBox.setFont(font)
        self.drawingGroupBox.setObjectName("drawingGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.drawingGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.transparencyButton = QtWidgets.QGroupBox(self.drawingGroupBox)
        self.transparencyButton.setObjectName("transparencyButton")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.transparencyButton)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.transparencySlider = QtWidgets.QSlider(self.transparencyButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transparencySlider.sizePolicy().hasHeightForWidth())
        self.transparencySlider.setSizePolicy(sizePolicy)
        self.transparencySlider.setMinimumSize(QtCore.QSize(30, 20))
        self.transparencySlider.setMaximumSize(QtCore.QSize(100, 20))
        self.transparencySlider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background-color: lightgray;  /* Light gray color for the handle */\n"
"    border: 1px solid #999999;    /* Border around the handle */\n"
"    width: 10px;                  /* Handle width */\n"
"    height: 10px;                 /* Handle height */\n"
"    border-radius: 5px;           /* Makes the handle circular */\n"
"    margin: -5px 0;               /* Centers the handle vertically */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: darkgray;   /* Dark gray for the area to the left of the handle */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background-color: rgb(241, 241, 241);  /* Light gray for the area to the right of the handle */\n"
"    border: 1px solid #999999;             /* Optional border */\n"
"}\n"
"")
        self.transparencySlider.setOrientation(QtCore.Qt.Horizontal)
        self.transparencySlider.setObjectName("transparencySlider")
        self.horizontalLayout_12.addWidget(self.transparencySlider)
        self.transparencyLabel = QtWidgets.QLabel(self.transparencyButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transparencyLabel.sizePolicy().hasHeightForWidth())
        self.transparencyLabel.setSizePolicy(sizePolicy)
        self.transparencyLabel.setMinimumSize(QtCore.QSize(30, 20))
        self.transparencyLabel.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.transparencyLabel.setFont(font)
        self.transparencyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.transparencyLabel.setObjectName("transparencyLabel")
        self.horizontalLayout_12.addWidget(self.transparencyLabel)
        self.gridLayout_4.addWidget(self.transparencyButton, 0, 5, 1, 1)
        self.fillShapeButton = QtWidgets.QPushButton(self.drawingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fillShapeButton.sizePolicy().hasHeightForWidth())
        self.fillShapeButton.setSizePolicy(sizePolicy)
        self.fillShapeButton.setMinimumSize(QtCore.QSize(50, 50))
        self.fillShapeButton.setMaximumSize(QtCore.QSize(50, 50))
        self.fillShapeButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fillShapeButton.setIcon(icon9)
        self.fillShapeButton.setIconSize(QtCore.QSize(30, 30))
        self.fillShapeButton.setObjectName("fillShapeButton")
        self.gridLayout_4.addWidget(self.fillShapeButton, 0, 0, 1, 1)
        self.arrangeButton = QtWidgets.QPushButton(self.drawingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrangeButton.sizePolicy().hasHeightForWidth())
        self.arrangeButton.setSizePolicy(sizePolicy)
        self.arrangeButton.setMinimumSize(QtCore.QSize(50, 50))
        self.arrangeButton.setMaximumSize(QtCore.QSize(50, 50))
        self.arrangeButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/layers (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrangeButton.setIcon(icon10)
        self.arrangeButton.setIconSize(QtCore.QSize(30, 30))
        self.arrangeButton.setObjectName("arrangeButton")
        self.gridLayout_4.addWidget(self.arrangeButton, 0, 4, 1, 1)
        self.shapeBackgroundColorFrame = QtWidgets.QFrame(self.drawingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shapeBackgroundColorFrame.sizePolicy().hasHeightForWidth())
        self.shapeBackgroundColorFrame.setSizePolicy(sizePolicy)
        self.shapeBackgroundColorFrame.setMinimumSize(QtCore.QSize(50, 4))
        self.shapeBackgroundColorFrame.setMaximumSize(QtCore.QSize(50, 4))
        self.shapeBackgroundColorFrame.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 100, 0);\n"
"border:1px;\n"
"\n"
"}")
        self.shapeBackgroundColorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shapeBackgroundColorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shapeBackgroundColorFrame.setObjectName("textBackgroundColorFrame_2")
        self.gridLayout_4.addWidget(self.shapeBackgroundColorFrame, 1, 0, 1, 1)
        self.borderThicknessSpinBox = QtWidgets.QSpinBox(self.drawingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borderThicknessSpinBox.sizePolicy().hasHeightForWidth())
        self.borderThicknessSpinBox.setSizePolicy(sizePolicy)
        self.borderThicknessSpinBox.setStyleSheet("QSpinBox {\n"
"    border: 2px solid rgb(154, 154, 154);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: rgb(240, 240, 240); /* Light background */\n"
"    color: rgb(50, 50, 50); /* Text color */\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    border-left: 1px solid rgb(154, 154, 154);\n"
"    background-color: rgb(220, 220, 220);\n"
"    width: 20px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    border-left: 1px solid rgb(154, 154, 154);\n"
"    background-color: rgb(220, 220, 220);\n"
"    width: 20px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(C:/Users/hamda/Desktop/GesturaApp versions/GesturaApp  version 0_2/gesturaTesting/Icons/Chevron up.svg); /* Replace with your resource path */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(C:/Users/hamda/Desktop/GesturaApp versions/GesturaApp  version 0_2/gesturaTesting/Icons/Chevron down.svg); /* Replace with your resource path */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border-color: rgb(100, 100, 100); /* Darker border on hover */\n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"")
        self.borderThicknessSpinBox.setObjectName("borderThicknessSpinBox")
        self.gridLayout_4.addWidget(self.borderThicknessSpinBox, 0, 3, 1, 1)
        self.borderColorButton = QtWidgets.QPushButton(self.drawingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borderColorButton.sizePolicy().hasHeightForWidth())
        self.borderColorButton.setSizePolicy(sizePolicy)
        self.borderColorButton.setMinimumSize(QtCore.QSize(50, 50))
        self.borderColorButton.setMaximumSize(QtCore.QSize(50, 50))
        self.borderColorButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/arrows.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.borderColorButton.setIcon(icon11)
        self.borderColorButton.setIconSize(QtCore.QSize(30, 30))
        self.borderColorButton.setObjectName("borderColorButton")
        self.gridLayout_4.addWidget(self.borderColorButton, 0, 1, 1, 1)
        self.lineWeightLabel = QtWidgets.QLabel(self.drawingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWeightLabel.sizePolicy().hasHeightForWidth())
        self.lineWeightLabel.setSizePolicy(sizePolicy)
        self.lineWeightLabel.setMinimumSize(QtCore.QSize(30, 30))
        self.lineWeightLabel.setMaximumSize(QtCore.QSize(30, 30))
        self.lineWeightLabel.setText("")
        self.lineWeightLabel.setPixmap(QtGui.QPixmap(":/Icons/Icons/width.svg"))
        self.lineWeightLabel.setScaledContents(True)
        self.lineWeightLabel.setObjectName("lineWeightLabel")
        self.gridLayout_4.addWidget(self.lineWeightLabel, 0, 2, 1, 1)
        self.borderColorFrame = QtWidgets.QFrame(self.drawingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borderColorFrame.sizePolicy().hasHeightForWidth())
        self.borderColorFrame.setSizePolicy(sizePolicy)
        self.borderColorFrame.setMinimumSize(QtCore.QSize(50, 4))
        self.borderColorFrame.setMaximumSize(QtCore.QSize(50, 4))
        self.borderColorFrame.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 0);\n"
"border:1px;\n"
"\n"
"}")
        self.borderColorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.borderColorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.borderColorFrame.setObjectName("textBackgroundColorFrame_3")
        self.gridLayout_4.addWidget(self.borderColorFrame, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.drawingGroupBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.tabWidget.addTab(self.homeTab, "")
        self.insertionTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertionTab.sizePolicy().hasHeightForWidth())
        self.insertionTab.setSizePolicy(sizePolicy)
        self.insertionTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.insertionTab.setObjectName("insertionTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.insertionTab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.insertionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
   
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.textGroupBox = QtWidgets.QGroupBox(self.frame_3)
        self.textGroupBox.setObjectName("textGroupBox")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.textGroupBox)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.insertTextButton = QtWidgets.QPushButton(self.textGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertTextButton.sizePolicy().hasHeightForWidth())
        self.insertTextButton.setSizePolicy(sizePolicy)
        self.insertTextButton.setMinimumSize(QtCore.QSize(60, 40))
        self.insertTextButton.setMaximumSize(QtCore.QSize(60, 50))
        self.insertTextButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/Icons/font.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertTextButton.setIcon(icon12)
        self.insertTextButton.setIconSize(QtCore.QSize(45, 45))
        self.insertTextButton.setObjectName("insertTextButton")
        self.horizontalLayout_14.addWidget(self.insertTextButton)
        self.horizontalLayout_13.addWidget(self.textGroupBox)
        self.imageGroupBox = QtWidgets.QGroupBox(self.frame_3)
        self.imageGroupBox.setObjectName("imageGroupBox")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.imageGroupBox)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.insertImageButton = QtWidgets.QPushButton(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertImageButton.sizePolicy().hasHeightForWidth())
        self.insertImageButton.setSizePolicy(sizePolicy)
        self.insertImageButton.setMinimumSize(QtCore.QSize(60, 50))
        self.insertImageButton.setMaximumSize(QtCore.QSize(60, 50))
        self.insertImageButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/Image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertImageButton.setIcon(icon13)
        self.insertImageButton.setIconSize(QtCore.QSize(45, 45))
        self.insertImageButton.setObjectName("insertImageButton")
        self.horizontalLayout_15.addWidget(self.insertImageButton)
        self.horizontalLayout_13.addWidget(self.imageGroupBox)
        self.videoGroupBox = QtWidgets.QGroupBox(self.frame_3)
        self.videoGroupBox.setObjectName("videoGroupBox")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.videoGroupBox)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.insertVideoButton = QtWidgets.QPushButton(self.videoGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertVideoButton.sizePolicy().hasHeightForWidth())
        self.insertVideoButton.setSizePolicy(sizePolicy)
        self.insertVideoButton.setMinimumSize(QtCore.QSize(60, 50))
        self.insertVideoButton.setMaximumSize(QtCore.QSize(60, 50))
        self.insertVideoButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/video.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertVideoButton.setIcon(icon14)
        self.insertVideoButton.setIconSize(QtCore.QSize(45, 45))
        self.insertVideoButton.setObjectName("insertVideoButton")
        self.horizontalLayout_16.addWidget(self.insertVideoButton)
        self.horizontalLayout_13.addWidget(self.videoGroupBox)
        self.modelGroupBox = QtWidgets.QGroupBox(self.frame_3)
        self.modelGroupBox.setObjectName("modelGroupBox")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.modelGroupBox)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.insertModelButton = QtWidgets.QPushButton(self.modelGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertModelButton.sizePolicy().hasHeightForWidth())
        self.insertModelButton.setSizePolicy(sizePolicy)
        self.insertModelButton.setMinimumSize(QtCore.QSize(60, 50))
        self.insertModelButton.setMaximumSize(QtCore.QSize(60, 50))
        self.insertModelButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/3d-modeling.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertModelButton.setIcon(icon15)
        self.insertModelButton.setIconSize(QtCore.QSize(45, 45))
        self.insertModelButton.setObjectName("insertModelButton")
        self.horizontalLayout_17.addWidget(self.insertModelButton)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        
        
        self.modelNameLineEdit = QtWidgets.QLineEdit(self.modelGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelNameLineEdit.sizePolicy().hasHeightForWidth())
        self.modelNameLineEdit.setSizePolicy(sizePolicy)
        self.modelNameLineEdit.setMinimumSize(QtCore.QSize(140, 0))
        self.modelNameLineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.modelNameLineEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.modelNameLineEdit.setFont(font)
        self.modelNameLineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(154, 154, 154);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: rgb(240, 240, 240); /* Light background */\n"
"    color: rgb(50, 50, 50); /* Text color */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: rgb(100, 100, 100); /* Darker border on hover */\n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(80, 80, 80); /* Focus border color */\n"
"    background-color: rgb(255, 255, 255); /* Lighter background on focus */\n"
"}\n"
"")
        self.modelNameLineEdit.setObjectName("modelNameLineEdit")
        self.horizontalLayout_17.addWidget(self.modelNameLineEdit)
        self.horizontalLayout_13.addWidget(self.modelGroupBox)
        self.shapeGroupBox = QtWidgets.QGroupBox(self.frame_3)
        self.shapeGroupBox.setObjectName("shapeGroupBox")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.shapeGroupBox)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.toolButton = QtWidgets.QToolButton(self.shapeGroupBox)
        self.toolButton.setMinimumSize(QtCore.QSize(50, 50))
        self.toolButton.setMaximumSize(QtCore.QSize(50, 50))
        self.toolButton.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/shapes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon17)
        self.toolButton.setIconSize(QtCore.QSize(40, 40))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_18.addWidget(self.toolButton)
        self.layerButton = QtWidgets.QPushButton(self.shapeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerButton.sizePolicy().hasHeightForWidth())
        self.layerButton.setSizePolicy(sizePolicy)
        self.layerButton.setMinimumSize(QtCore.QSize(60, 50))
        self.layerButton.setMaximumSize(QtCore.QSize(60, 50))
        self.layerButton.setText("")
        self.layerButton.setIcon(icon10)
        self.layerButton.setIconSize(QtCore.QSize(45, 45))
        self.layerButton.setObjectName("layerButton")
        self.horizontalLayout_18.addWidget(self.layerButton)
        self.horizontalLayout_13.addWidget(self.shapeGroupBox)
        self.slideGroupBox = QtWidgets.QGroupBox(self.frame_3)
        self.slideGroupBox.setObjectName("slideGroupBox")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.slideGroupBox)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.insertSlideButton = QtWidgets.QPushButton(self.slideGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertSlideButton.sizePolicy().hasHeightForWidth())
        self.insertSlideButton.setSizePolicy(sizePolicy)
        self.insertSlideButton.setMinimumSize(QtCore.QSize(60, 50))
        self.insertSlideButton.setMaximumSize(QtCore.QSize(60, 50))
        self.insertSlideButton.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/slides.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insertSlideButton.setIcon(icon18)
        self.insertSlideButton.setIconSize(QtCore.QSize(45, 45))
        self.insertSlideButton.setObjectName("insertSlideButton")
        self.horizontalLayout_19.addWidget(self.insertSlideButton)
        self.horizontalLayout_13.addWidget(self.slideGroupBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.horizontalLayout_7.addWidget(self.frame_3)
        self.tabWidget.addTab(self.insertionTab, "")
        self.transitionTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transitionTab.sizePolicy().hasHeightForWidth())
        self.transitionTab.setSizePolicy(sizePolicy)
        self.transitionTab.setObjectName("transitionTab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.transitionTab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.transitionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
       
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.tabWidget.addTab(self.transitionTab, "")
        self.animationTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationTab.sizePolicy().hasHeightForWidth())
        self.animationTab.setSizePolicy(sizePolicy)
        self.animationTab.setObjectName("animationTab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.animationTab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.animationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_5.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
      
        self.horizontalLayout_9.addWidget(self.frame_5)
        self.tabWidget.addTab(self.animationTab, "")
        self.presentationTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presentationTab.sizePolicy().hasHeightForWidth())
        self.presentationTab.setSizePolicy(sizePolicy)
        self.presentationTab.setObjectName("presentationTab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.presentationTab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_6 = QtWidgets.QFrame(self.presentationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_6.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:10;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.showSlideGroupBox = QtWidgets.QGroupBox(self.frame_6)
        self.showSlideGroupBox.setObjectName("showSlideGroupBox")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.showSlideGroupBox)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.presentButton = QtWidgets.QPushButton(self.showSlideGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presentButton.sizePolicy().hasHeightForWidth())
        self.presentButton.setSizePolicy(sizePolicy)
        self.presentButton.setMinimumSize(QtCore.QSize(60, 50))
        self.presentButton.setMaximumSize(QtCore.QSize(60, 50))
        self.presentButton.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/presentation (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.presentButton.setIcon(icon19)
        self.presentButton.setIconSize(QtCore.QSize(45, 45))
        self.presentButton.setObjectName("presentButton")
        self.horizontalLayout_20.addWidget(self.presentButton)
        self.presentFromCurrentButton = QtWidgets.QPushButton(self.showSlideGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presentFromCurrentButton.sizePolicy().hasHeightForWidth())
        self.presentFromCurrentButton.setSizePolicy(sizePolicy)
        self.presentFromCurrentButton.setMinimumSize(QtCore.QSize(60, 50))
        self.presentFromCurrentButton.setMaximumSize(QtCore.QSize(60, 50))
        self.presentFromCurrentButton.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/presentation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.presentFromCurrentButton.setIcon(icon20)
        self.presentFromCurrentButton.setIconSize(QtCore.QSize(45, 45))
        self.presentFromCurrentButton.setObjectName("presentFromCurrentButton")
        self.horizontalLayout_20.addWidget(self.presentFromCurrentButton)
        self.horizontalLayout_21.addWidget(self.showSlideGroupBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.horizontalLayout_10.addWidget(self.frame_6)
        self.tabWidget.addTab(self.presentationTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3.addWidget(self.titleFrame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(8, -1, 8, -1)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_9.setStyleSheet("QFrame {\n"
"    \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 rgba(243, 200, 205, 255), stop: 1 rgba(181, 210, 228, 255));\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("QFrame{\n"
"background-color:rgba(255, 255, 255, 100);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.slideScrollZone = SlideScrollZone(self.frame_13)
        self.slideScrollZone.setStyleSheet("QScrollArea {\n"
"    background: transparent; /* Make the scroll area background transparent */\n"
"    border: none;           /* Optional: remove border if any */\n"
"}\n"
"\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: transparent; /* Make the scrollbar background transparent */\n"
"    border: none;           /* Optional: remove border if any */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: rgb(150, 150, 150); /* Optional: color for the scrollbar handle */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical, \n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"")
        self.slideScrollZone.setWidgetResizable(True)
        self.slideScrollZone.setObjectName("slideScrollZone")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 264, 477))
        self.scrollAreaWidgetContents.setStyleSheet("QWidget{\n"
"\n"
"background-color:transparent;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        
        self.verticalLayout_8.addWidget(self.slideScrollZone)
        self.workSpace = WorkSpace(self.slideScrollZone,MainWindow,self.centralwidget)
        self.workSpace.setToolTip("")
        self.workSpace.setObjectName("workSpace")
        self.gridLayout.addWidget(self.workSpace, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.gridLayout.addWidget(self.frame_9, 0, 0, 4, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid white;  /* Sets a 2px solid border with a blue color */\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 6, 1, 1)
        self.commentButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentButton.sizePolicy().hasHeightForWidth())
        self.commentButton.setSizePolicy(sizePolicy)
        self.commentButton.setMinimumSize(QtCore.QSize(35, 30))
        self.commentButton.setMaximumSize(QtCore.QSize(20, 30))
        self.commentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commentButton.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/Message square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commentButton.setIcon(icon21)
        self.commentButton.setIconSize(QtCore.QSize(30, 30))
        self.commentButton.setObjectName("commentButton")
       
        self.gridLayout.addWidget(self.commentButton, 0, 6, 1, 1)
        self.gridLayout.setContentsMargins(8, 0, 8, 10)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.components=[self.frame,self.frame_2,self.frame_3,self.frame_4,self.frame_5,self.frame_6,self.frame_7,self.frame_9,self.commentButton,self.pushButton,self.textEdit]
        for frame in self.components:
                shadow = QGraphicsDropShadowEffect()
                shadow.setBlurRadius(15)
                shadow.setColor(QColor(0, 0, 0, 100))
                shadow.setOffset(5, 5)
                frame.setGraphicsEffect(shadow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " "))
        self.seachEditLine.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.presentationNameLabel.setText(_translate("MainWindow", "My first presentation-Gestura"))
        self.appNameLabel.setText(_translate("MainWindow", "Gestura"))
        self.pushButton.setText(_translate("MainWindow", "Share"))
        self.userNameLabel.setText(_translate("MainWindow", "Name"))
        self.userAddressLabel.setText(_translate("MainWindow", "user@gmail.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FileTab), _translate("MainWindow", "   File    "))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.FileTab), _translate("MainWindow", "File"))
        self.fontGroupBox.setTitle(_translate("MainWindow", "Font"))
        self.textColorButton.setToolTip(_translate("MainWindow", "Font color"))
        self.underlineButton.setToolTip(_translate("MainWindow", "Underline"))
        self.boldButton.setToolTip(_translate("MainWindow", "Bold"))
        self.strikeButton.setToolTip(_translate("MainWindow", "Strikethrough"))
        self.fontComboBox.setToolTip(_translate("MainWindow", "Font"))
        self.fontSizeSpinBox.setToolTip(_translate("MainWindow", "Font size"))
        self.italicButton.setToolTip(_translate("MainWindow", "Italic"))
        self.paragraphGroupBox.setTitle(_translate("MainWindow", "Paragraph"))
        self.alignLeftButton.setToolTip(_translate("MainWindow", "Align left"))
        self.alignCenterButton.setToolTip(_translate("MainWindow", "Align center"))
        self.alignRightButton.setToolTip(_translate("MainWindow", "Align right"))
        self.drawingGroupBox.setTitle(_translate("MainWindow", "Drawing"))
        self.transparencyButton.setTitle(_translate("MainWindow", "Transparency"))
        self.transparencyLabel.setText(_translate("MainWindow", "0%"))
        self.lineWeightLabel.setToolTip(_translate("MainWindow", "Border thickness"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), _translate("MainWindow", "   Home    "))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.homeTab), _translate("MainWindow", "Home"))
        self.insertionTab.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.textGroupBox.setTitle(_translate("MainWindow", "Text"))
        self.insertTextButton.setToolTip(_translate("MainWindow", "insert text zone"))
        self.imageGroupBox.setTitle(_translate("MainWindow", "Image"))
        self.insertImageButton.setToolTip(_translate("MainWindow", "Insert image"))
        self.videoGroupBox.setTitle(_translate("MainWindow", "Video"))
        self.insertVideoButton.setToolTip(_translate("MainWindow", "Insert video"))
        self.modelGroupBox.setTitle(_translate("MainWindow", "3D Model"))
        self.insertModelButton.setToolTip(_translate("MainWindow", "Insert 3D model"))
        
        self.modelNameLineEdit.setPlaceholderText(_translate("MainWindow", "Enter model name..."))
        self.shapeGroupBox.setTitle(_translate("MainWindow", "Shape"))
        self.layerButton.setToolTip(_translate("MainWindow", "Arrange shapes"))
        self.slideGroupBox.setTitle(_translate("MainWindow", "Slide"))
        self.insertSlideButton.setToolTip(_translate("MainWindow", "Insert slide"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.insertionTab), _translate("MainWindow", "     Insert        "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transitionTab), _translate("MainWindow", "     Transitions      "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.animationTab), _translate("MainWindow", "      Animations      "))
        self.showSlideGroupBox.setTitle(_translate("MainWindow", "Show slides"))
        self.presentButton.setToolTip(_translate("MainWindow", "Present from begining"))
        self.presentFromCurrentButton.setToolTip(_translate("MainWindow", "Present from current slide"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.presentationTab), _translate("MainWindow", "       Presentation       "))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Add a comment..."))
        self.commentButton.setToolTip(_translate("MainWindow", "Add comment"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
